### ISSUE TITLE
C'est les vacances

### ISSUE THREAD

**Issue by nathan-rabet** [nathan-rabet/linux-cryptFS-module#30]
# C'est ~~les vacances~~ la SUMMER SCHOOL

Les gars on va à l'étranger pendant 1 mois... donc svp **profitez de votre séjour** et on reprendra ce projet après.

Il est donc **interdit de faire des commits et ce jusqu'à début août** !

## Autorisation exceptionnelle pour faire des commits

Vous êtes autorisé à faire des commits uniquement si :

- Vous n'avez pas de soirée de prévue
- Vous n'avez rien de prévu
- **Vraiment vraiment RIEN** d'autre à faire !

Chaque commit ne respectant pas ses 3 règles **sera sévèrement sanctionné**.

Cordialement la direction.

**Comment by icare-sh** [comment]
Depois de apenas 3 dias no porto dormi 5 minutos. ele trabalha duro.

Boas festas.
Para futuras edições e compromissos, farei em português. eu esqueci francês

**Comment by nathan-rabet** [comment]
> Depois de apenas 3 dias no porto dormi 5 minutos. ele trabalha duro.
> 
> Boas festas.
> Para futuras edições e compromissos, farei em português. eu esqueci francês

Seems legit. 😎

**Comment by nathan-rabet** [comment]
C'est plus les vacances : au boulot !
