### ISSUE TITLE
Github Actions workflow : impossible de compiler (OpenSSL)

### ISSUE THREAD

**Issue by nathan-rabet** [nathan-rabet/linux-cryptFS-module#42]
# Problème

```c
/home/runner/work/linux-cryptFS-module/linux-cryptFS-module/tests/criterion/crypto_disk_test.c:25:18: error: implicit declaration of function ‘EVP_PKEY_eq’; did you mean ‘EVP_PKEY_new’? [-Werror=implicit-function-declaration]
   25 |     cr_assert_eq(EVP_PKEY_eq(rsa_keypair, rsa_keypair_loaded), 1);
      |                  ^~~~~~~~~~~
```

Comme vous pouvez le voir dans [cette sortie de journal de la CI](https://github.com/nathan-rabet/linux-cryptFS-module/runs/8233919147?check_suite_focus=true), la machine virtuelle n'arrive pas à compiler le projet, plus précisement la partie OpenSSL.

> Malgré le fait que les paquets `openssl` et `libssl-dev` soient installés..

**Comment by nathan-rabet** [comment]
Je précise que les tests compilent sur ma machine *obviously*.

**Comment by icare-sh** [comment]
Il faut installer la lib openssl-dev. 
Pour les environnements ubuntu/debian un ```apt install libssl-dev``` régle le soucis. 

Je pense que c'est un element important à marquer dans la documentation, notamment dans les prérequis pour pouvoir compiler le projet.

PS: sur mon archlinux j'arrive pas non plus à compiler à cause de la lib openssl. Il se trouve qu'il y'a certains ```include.h``` qui manquent dans ```/usr/includes/openssl```.

Pour compiler le projet je passe donc par un container Docker.

**Comment by icare-sh** [comment]
Je propose pour palier à ça  qu'on précise juste dans les prérequies qu'il faut installer la lib openssl-dev. 

Qu'est ce que vous en pensez ?

**Comment by nathan-rabet** [comment]
> Je propose pour palier à ça  qu'on précise juste dans les prérequies qu'il faut installer la lib openssl-dev. 
> 
> Qu'est ce que vous en pensez ?

J'installe déjà `libssl-dev` sur la CI... et pourtant ça ne marche toujours pas...

**Comment by nathan-rabet** [comment]
Problème résolu avec le commit [5a59f5d](https://github.com/nathan-rabet/linux-cryptFS-module/commit/5a59f5d652c6b565f5ec6fc4ab7da82060118792).

La CI utilisait une VM d'Ubuntu qui utilisait la version 1.1.1q de OPENSSL... alors que nous utilisons des fonctions issues de la version 3.0.0.
